import Head from 'next/head';
import React from 'react';

const Header = (props) => {
    return (
        <section>
            <Head>
                <title>{props.title} - Next Node Chat</title>
                <meta name="description" content="Generated by Next Node Chat" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </section>
    );
}
export default Header;