import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css'

export default function Home() {
  return (
    <section style={{padding: "0 2rem"}}>
      <Head>
        <title>Next Node Chat</title>
        <meta name="description" content="Generated by Next Node Chat" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </section>
  )
}
